### PR TITLE
games-board/aisleriot: Version bumb to 3.22.22 from 3.22.7

### PR DESCRIPTION
**Pull request by Archetypic**
* Meson for this version

* More recent versions on Gitlab

* Include option for `docs`

* Multiple licenses

* Increment version requirements for dependencies

### CODE REVIEW

**Comment by Archetypic** [comment]
Including `-Dguile=2.2` in `MESON_SRC_CONFIGURE_PARAMS` results in:
```
[35;01m===[0m Running ebuild phase killold as root:root...
[35;01m===[0m Starting builtin_killold
[35;01m===[0m Done builtin_killold
[35;01m===[0m Completed ebuild phase killold
[35;01m===[0m Running ebuild phases init saveenv as paludisbuild:paludisbuild...
[35;01m===[0m Starting builtin_init
[35;01m===[0m Done builtin_init
[35;01m===[0m Starting builtin_saveenv
[35;01m===[0m Done builtin_saveenv
[35;01m===[0m Completed ebuild phases init saveenv
[35;01m===[0m Running ebuild phases loadenv setup saveenv as root:root...
[35;01m===[0m Starting builtin_loadenv
[35;01m===[0m Done builtin_loadenv
[35;01m===[0m Starting pkg_setup
export LC_ALL=en_US.UTF-8
[35;01m===[0m Done pkg_setup
[35;01m===[0m Starting builtin_saveenv
[35;01m===[0m Done builtin_saveenv
[35;01m===[0m Completed ebuild phases loadenv setup saveenv
[35;01m===[0m Running ebuild phases loadenv unpack saveenv as paludisbuild:paludisbuild...
[35;01m===[0m Starting builtin_loadenv
[35;01m===[0m Done builtin_loadenv
[35;01m===[0m Starting src_unpack
>>> Unpacking aisleriot-3.22.22.tar.gz to /var/tmp/paludis/build/games-board-aisleriot-3.22.22/work
tar zxf /var/cache/paludis/distfiles/aisleriot-3.22.22.tar.gz --no-same-owner
mkdir -p /var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/_build
[35;01m===[0m Done src_unpack
[35;01m===[0m Starting builtin_saveenv
[35;01m===[0m Done builtin_saveenv
[35;01m===[0m Completed ebuild phases loadenv unpack saveenv
[35;01m===[0m Running ebuild phases loadenv prepare saveenv as paludisbuild:paludisbuild...
[35;01m===[0m Starting builtin_loadenv
[35;01m===[0m Done builtin_loadenv
[35;01m===[0m Starting src_prepare
cd /var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/aisleriot-3.22.22
[35;01m===[0m Done src_prepare
[35;01m===[0m Starting builtin_saveenv
[35;01m===[0m Done builtin_saveenv
[35;01m===[0m Completed ebuild phases loadenv prepare saveenv
[35;01m===[0m Running ebuild phases loadenv configure saveenv as paludisbuild:paludisbuild...
[35;01m===[0m Starting builtin_loadenv
[35;01m===[0m Done builtin_loadenv
[35;01m===[0m Starting src_configure
cat
meson --prefix=/usr --bindir=/usr/x86_64-pc-linux-musl/bin --sbindir=/usr/x86_64-pc-linux-musl/bin --libdir=/usr/x86_64-pc-linux-musl/lib --libexecdir=/usr/x86_64-pc-linux-musl/libexec --includedir=/usr/x86_64-pc-linux-musl/include --sysconfdir=/etc --datadir=/usr/share --mandir=/usr/share/man --default-library=shared --native-file meson-native.txt --wrap-mode=nodownload -Dbinreloc=false -Ddefault_theme=gnomangelo_bitmap.svgz -Ddefault_theme_format=svg-rsvg -Ddbg=false -Ddbgui=false -Dguile=2.2 -Dgconf=false -Dhelp_format=html -Dtheme_fixed=true -Dtheme_kde=false -Dtheme_pysol=false -Dtheme_svg_qtsvg=false -Dtheme_svg_rsvg=true -Ddocs=false -Dsound=false /var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/aisleriot-3.22.22
[1mThe Meson build system[0m
Version: 0.62.1
Source dir: [1m/var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/aisleriot-3.22.22[0m
Build dir: [1m/var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/_build[0m
Build type: [1mnative build[0m
Project name: [1maisleriot[0m
Project version: [1m3.22.22[0m
C compiler for the host machine: [1mx86_64-pc-linux-musl-cc[0m (gcc 11.3.0 "x86_64-pc-linux-musl-gcc (GCC) 11.3.0")
C linker for the host machine: [1mx86_64-pc-linux-musl-cc[0m ld.bfd 2.38
C++ compiler for the host machine: [1mx86_64-pc-linux-musl-c++[0m (gcc 11.3.0 "x86_64-pc-linux-musl-g++ (GCC) 11.3.0")
C++ linker for the host machine: [1mx86_64-pc-linux-musl-c++[0m ld.bfd 2.38
Host machine cpu family: [1mx86_64[0m
Host machine cpu: [1mx86_64[0m
Compiler for C supports arguments -Wall: [1;32mYES[0m 
Compiler for C supports arguments -Wcast-align: [1;32mYES[0m 
Compiler for C supports arguments -Wempty-body: [1;32mYES[0m 
Compiler for C supports arguments -Wformat-signedness: [1;32mYES[0m 
Compiler for C supports arguments -Werror=implicit-function-declaration: [1;32mYES[0m 
Compiler for C supports arguments -Wextra: [1;32mYES[0m 
Compiler for C supports arguments -Wformat-nonliteral: [1;32mYES[0m 
Compiler for C supports arguments -Winit-self: [1;32mYES[0m 
Compiler for C supports arguments -Wlogical-op: [1;32mYES[0m 
Compiler for C supports arguments -Wmissing-declarations: [1;32mYES[0m 
Compiler for C supports arguments -Wmissing-format-attribute: [1;32mYES[0m 
Compiler for C supports arguments -Wno-missing-field-initializers: [1;32mYES[0m 
Compiler for C supports arguments -Wno-switch-enum: [1;32mYES[0m 
Compiler for C supports arguments -Wno-unused-parameter: [1;32mYES[0m 
Compiler for C supports arguments -Wpacked: [1;32mYES[0m 
Compiler for C supports arguments -Wpointer-arith: [1;32mYES[0m 
Compiler for C supports arguments -Wshadow: [1;32mYES[0m 
Compiler for C supports arguments -Wstrict-aliasing=2: [1;32mYES[0m 
Compiler for C supports arguments -Wundef: [1;32mYES[0m 
Compiler for C supports arguments -Wuninitialized: [1;32mYES[0m 
Compiler for C supports arguments -Wunsafe-loop-optimizations: [1;32mYES[0m 
Compiler for C supports arguments -Wwrite-strings: [1;32mYES[0m 
Compiler for C supports arguments -fno-common: [1;32mYES[0m 
Compiler for C supports arguments -fno-strict-aliasing: [1;32mYES[0m 
Compiler for C supports arguments -Waggregate-return: [1;32mYES[0m 
Compiler for C supports arguments -Wimplicit: [1;32mYES[0m 
Compiler for C supports arguments -Wmissing-prototypes: [1;32mYES[0m 
Compiler for C supports arguments -Wnested-externs: [1;32mYES[0m 
Compiler for C supports arguments -Wold-style-definition: [1;32mYES[0m 
Compiler for C supports arguments -Wsign-compare: [1;32mYES[0m 
Compiler for C supports arguments -Wstrict-prototypes: [1;32mYES[0m 
Compiler for C++ supports arguments -Wall: [1;32mYES[0m 
Compiler for C++ supports arguments -Wcast-align: [1;32mYES[0m 
Compiler for C++ supports arguments -Wempty-body: [1;32mYES[0m 
Compiler for C++ supports arguments -Wformat-signedness: [1;32mYES[0m 
Compiler for C++ supports arguments -Werror=implicit-function-declaration: [1;32mYES[0m 
Compiler for C++ supports arguments -Wextra: [1;32mYES[0m 
Compiler for C++ supports arguments -Wformat-nonliteral: [1;32mYES[0m 
Compiler for C++ supports arguments -Winit-self: [1;32mYES[0m 
Compiler for C++ supports arguments -Wlogical-op: [1;32mYES[0m 
Compiler for C++ supports arguments -Wmissing-declarations: [1;32mYES[0m 
Compiler for C++ supports arguments -Wmissing-format-attribute: [1;32mYES[0m 
Compiler for C++ supports arguments -Wno-missing-field-initializers: [1;32mYES[0m 
Compiler for C++ supports arguments -Wno-switch-enum: [1;32mYES[0m 
Compiler for C++ supports arguments -Wno-unused-parameter: [1;32mYES[0m 
Compiler for C++ supports arguments -Wpacked: [1;32mYES[0m 
Compiler for C++ supports arguments -Wpointer-arith: [1;32mYES[0m 
Compiler for C++ supports arguments -Wshadow: [1;32mYES[0m 
Compiler for C++ supports arguments -Wstrict-aliasing=2: [1;32mYES[0m 
Compiler for C++ supports arguments -Wundef: [1;32mYES[0m 
Compiler for C++ supports arguments -Wuninitialized: [1;32mYES[0m 
Compiler for C++ supports arguments -Wunsafe-loop-optimizations: [1;32mYES[0m 
Compiler for C++ supports arguments -Wwrite-strings: [1;32mYES[0m 
Compiler for C++ supports arguments -fno-common: [1;32mYES[0m 
Compiler for C++ supports arguments -fno-strict-aliasing: [1;32mYES[0m 
../aisleriot-3.22.22/meson.build:243: [1;33mWARNING:[0m Consider using the built-in warning_level option instead of using "-Wall".
../aisleriot-3.22.22/meson.build:243: [1;33mWARNING:[0m Consider using the built-in warning_level option instead of using "-Wextra".
../aisleriot-3.22.22/meson.build:244: [1;33mWARNING:[0m Consider using the built-in warning_level option instead of using "-Wall".
../aisleriot-3.22.22/meson.build:244: [1;33mWARNING:[0m Consider using the built-in warning_level option instead of using "-Wextra".
[1;33mWARNING:[0m You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300

../aisleriot-3.22.22/meson.build:329:2: [1;31mERROR:[0m Unknown method "to_string" in object <[StringHolder] holds [str]: '2.2'> of type StringHolder.

A full log can be found at [1m/var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/_build/meson-logs/meson-log.txt[0m

!!! ERROR in games-board/aisleriot-3.22.22::sardemff7:
!!! In edo at line 1449
!!! meson --prefix=/usr --bindir=/usr/x86_64-pc-linux-musl/bin --sbindir=/usr/x86_64-pc-linux-musl/bin --libdir=/usr/x86_64-pc-linux-musl/lib --libexecdir=/usr/x86_64-pc-linux-musl/libexec --includedir=/usr/x86_64-pc-linux-musl/include --sysconfdir=/etc --datadir=/usr/share --mandir=/usr/share/man --default-library=shared --native-file meson-native.txt --wrap-mode=nodownload -Dbinreloc=false -Ddefault_theme=gnomangelo_bitmap.svgz -Ddefault_theme_format=svg-rsvg -Ddbg=false -Ddbgui=false -Dguile=2.2 -Dgconf=false -Dhelp_format=html -Dtheme_fixed=true -Dtheme_kde=false -Dtheme_pysol=false -Dtheme_svg_qtsvg=false -Dtheme_svg_rsvg=true -Ddocs=false -Dsound=false /var/tmp/paludis/build/games-board-aisleriot-3.22.22/work/aisleriot-3.22.22 failed

!!! Call stack:
!!!    * paludis_die_unless_nonfatal_func (/var/tmp/paludis/build/games-board-aisleriot-3.22.22/temp/loadsaveenv:2505)
!!!    * edo (/var/tmp/paludis/build/games-board-aisleriot-3.22.22/temp/loadsaveenv:1449)
!!!    * exmeson (/var/tmp/paludis/build/games-board-aisleriot-3.22.22/temp/loadsaveenv:2008)
!!!    * meson_src_configure (/var/tmp/paludis/build/games-board-aisleriot-3.22.22/temp/loadsaveenv:2349)
!!!    * src_configure (/var/tmp/paludis/build/games-board-aisleriot-3.22.22/temp/loadsaveenv:2904)
!!!    * exheres_internal_configure (/usr/x86_64-pc-linux-musl/libexec/paludis/exheres-0/src_configure.bash:68)
!!!    * ebuild_main (/usr/x86_64-pc-linux-musl/libexec/paludis/ebuild.bash:727)
!!!    * main (/usr/x86_64-pc-linux-musl/libexec/paludis/ebuild.bash:750)

diefunc: making ebuild PID 27982 exit with error
die trap: exiting with error.
```

Option `guile` defined in `${WORK}/meson_options.txt` as:
```
...
option(
  'guile',
  type: 'combo',
  choices: ['3.0', '2.2', '2.0', 'auto',],
  value: 'auto',
  description: 'Which guile version to use',
)
...
```

**Comment by sardemff7** [comment]
I’ll be weirdly partial here but I’d rather use “Bump” than “Increment” which sounds weird to me here

I’d love the Guile option to be fixed too as we really don’t like automagics
Seems like removing the `to_string()` in the `meson.build` would be enough as the option should be a string already

**Comment by Archetypic** [comment]
I merely bump exheres for experience.
It is never an issue to submit a few merge requests a week.

**Comment by sardemff7** [comment]
Great! Thanks :-)

**Pull request merged**
