### PR TITLE
geany: Bump to 2.0

### PR DESCRIPTION
**Pull request by Yoda-BZH**
geany (editor and plugins) v2.0 is available since october 2023

Plus, plugin git-changebar wasn't compiling in 1.38. It's now fixed.

### CODE REVIEW

**Comment by sardemff7** [comment]
Thanks for the work

A few comments:
- no Conventional Commits nonsense in here, please :grin: 
- when you bump a package:
  - just bump dependencies in the same commit
  - remove the revision (the `-rX` part), which is Exherbo-specific and used to force a rebuild (because Paludis will see it as “a newer version”) when you fix a package but the upstream version didn’t change
- for updates, I use the `<package>: Bump to <version>` format (with this case, capital B)

**Comment by Yoda-BZH** [comment]
everything should be fixed :)

**Comment by sardemff7** [comment]
Good, but I’d like two commits though :smile:

**Comment by sardemff7** [comment]
Tip for next time: one commit per package is nicer, but one Pull Request for both commits is fine ^^

**Pull request merged**
